name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - master  # تم التغيير هنا إلى master

jobs:
  deploy_to_firebase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: 'adahi-manager' # هذا هو معرف مشروعك الذي أكدناه
          channelId: live
